source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

target 'MQTTClientmacOS' do
	pod 'SocketRocket', '0.5.1'
    
    target 'MQTTClientmacOSTests' do
        inherit! :search_paths
    end
end

target 'MQTTClientiOS' do
    pod 'SocketRocket', '0.5.1'
    
    target 'MQTTClientiOSTests' do
        inherit! :search_paths
    end
end

target 'MQTTClienttvOS' do
    pod 'SocketRocket', '0.5.1'
    
    target 'MQTTClienttvOSTests' do
        inherit! :search_paths
    end
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
      end
    end
  end
